# Generated by Django 6.0.4 on 2026-06-04 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0006_faculty_contentstore_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="Timetable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semester", models.CharField(max_length=20)),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                            ("Sunday", "Sunday"),
                        ],
                        max_length=15,
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("classroom", models.CharField(blank=True, default="", max_length=50)),
                (
                    "is_essential",
                    models.BooleanField(
                        default=False, verbose_name="Essential Lecture"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetables",
                        to="cms.department",
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timetable_classes",
                        to="cms.faculty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Timetable Entry",
                "verbose_name_plural": "Timetable Entries",
                "ordering": ["day_of_week", "start_time"],
            },
        ),
    ]
