"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-!d1zo^!#(kd1rb7d7p&#a-(#!ly-*v(4^*q_^a$l)c3!76qr#5"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "unfold",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "cms"
]

UNFOLD = {
    "SITE_TITLE": "College Management Admin",
    "SITE_HEADER": "College Admin Portal",
    "SITE_SYMBOL": "school",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "COLORS": {
        "primary": {
            "50": "244 245 247",
            "100": "224 225 221",   # Eclipse Glow (#E0E1DD)
            "200": "186 197 212",
            "300": "145 163 186",
            "400": "119 141 169",   # Eclipse Light (#778DA9)
            "500": "65 90 119",     # Eclipse Steel (#415A77)
            "600": "52 73 99",
            "700": "39 56 78",
            "800": "27 38 59",      # Eclipse Navy (#1B263B)
            "900": "13 27 42",      # Eclipse Deep (#0D1B2A)
            "950": "8 16 26",
        },
        "accent": {
            "50": "255 242 242",
            "100": "255 224 224",
            "200": "255 184 184",
            "300": "255 138 138",
            "400": "255 107 107",   # Eclipse Coral/Red (#ff6b6b)
            "500": "239 68 68",
            "600": "220 38 38",
            "700": "185 28 28",
            "800": "153 27 27",
            "900": "127 29 29",
            "950": "69 10 10",
        },
        "neutral": {
            "50": "248 250 252",
            "100": "241 245 249",
            "200": "226 232 240",
            "300": "203 213 225",
            "400": "148 163 184",
            "500": "100 116 139",
            "600": "71 85 105",
            "700": "51 65 85",
            "800": "30 41 59",
            "900": "15 23 42",
            "950": "2 6 23",
        }
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Academic Administration",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Departments",
                        "icon": "corporate_fare",
                        "link": "/admin/cms/department/",
                    },
                    {
                        "title": "Faculty Members",
                        "icon": "badge",
                        "link": "/admin/cms/faculty/",
                    },
                    {
                        "title": "Student Directory",
                        "icon": "group",
                        "link": "/admin/cms/student/",
                    },
                    {
                        "title": "Timetables & Schedules",
                        "icon": "calendar_month",
                        "link": "/admin/cms/timetable/",
                    },
                ],
            },
            {
                "title": "Performance & Records",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Grades & Results",
                        "icon": "workspace_premium",
                        "link": "/admin/cms/result/",
                    },
                    {
                        "title": "Daily Attendance",
                        "icon": "assignment_turned_in",
                        "link": "/admin/cms/attendance/",
                    },
                ],
            },
            {
                "title": "Communication Hub",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Notice Board",
                        "icon": "campaign",
                        "link": "/admin/cms/notice/",
                    },
                    {
                        "title": "Notice Reads",
                        "icon": "visibility",
                        "link": "/admin/cms/noticeread/",
                    },
                    {
                        "title": "Content Library",
                        "icon": "library_books",
                        "link": "/admin/cms/contentstore/",
                    },
                    {
                        "title": "Student Messages",
                        "icon": "chat",
                        "link": "/admin/cms/message/",
                    },
                ],
            },
        ],
    },
}


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "cms.context_processors.student_nav_context",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]